### ISSUE TITLE
メッセージが出続けます。

### ISSUE THREAD

**Issue by himeyon** [tekka/ParallelHybridApp_card#2]
アプリ起動すると、無限に↓が出続けます。。。

![image](https://user-images.githubusercontent.com/4468822/108051523-59408680-708e-11eb-87ef-dd29af7ca801.png)

**Comment by tekka** [comment]
HTTPSのページからローカルWebサーバーに接続したときに、混在コンテンツと判定されるのを回避するため
HTTPではなくHTTPSでWebサーバーを起動していました。
本現象は上記処理に用いる証明書の更新不具合によるものです。

最新のブラウザではHTTPS→HTTPローカルホストに接続しても
混在コンテンツと判定されなくなったため
上記処理を削除し、HTTPでWebサーバーを起動するように修正しました。

アプリケーションの再ダウンロードをお願いいたします。

**Comment by himeyon** [comment]
@tekka 
ありがとうございます！
